#spring.application.name:
#  "spring-boot-spark-streaming-kafka-sample"
## LOGGING
#logging.level.root=info
#logging.path=/applog/spring-boot-spark-streaming-kafka-sample
##spark config start
#spark.driver.memory=32g
#spark.worker.memory=25g
#spark.executor.memory=25g
#spark.rpc.message.maxSize=1024
##spark master
##spark.master = spark://10.222.17.21:7077
##spark topics ','号分割
#spark.kafka.topics = news
##kafka集群地址，'，'号分割
#kafka.broker.list = 10.222.17.21:19092
##从kafka拉数据的间隔时间，单位 S
#spark.stream.kafka.durations=10
#spark config end




kafka.auto.offset.reset:
  "earliest"
#latest,earliest
kafka.group.id:
  "sparkstreaming-kafka10"



kafka.metadata.broker.list:
  "urs-offline1.dg.163.org:9092"
kafka.topics:
  "jgctopic1"


#kafka.topics=1mytopic
#kafka.metadata.broker.list=namenode1:9092




spark.master:
  "local[2]"
spark.appname:
  "SparkStreamingKafka"
spark.seconds:
  1
